# Generated by Django 3.1 on 2020-08-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200821_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
