# Generated by Django 3.1 on 2020-08-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200822_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(upload_to='img', verbose_name='Картинка'),
        ),
    ]
